# whitelist
branches:
  only:
    - develop

language: android
jdk: oraclejdk7
env:
  matrix:
    - ANDROID_TARGET=android-19  ANDROID_ABI=armeabi-v7a

android:
  components:
    - build-tools-19.0.0

before_install:
    - chmod +x ./android/CRIMP/gradlew