# whitelist
branches:
  only:
    - develop

language: android
env:
  matrix:
    - ANDROID_TARGET=android-19  ANDROID_ABI=armeabi-v7a

android:
  components:
    - build-tools-19.0.0

before_install:
    - chmod +x ./android/CRIMP/gradlew

script:
- echo $ADB_INSTALL_TIMEOUT
- android list target
- ./android/CRIMP/gradlew --info build