mongo:
  image: mongo
  command: mongod --smallfiles --oplogSize 128

crimp:
  image: leedongwei/crimp-dev:latest
  environment:
    - PORT=3000
    - ROOT_URL=http://localhost:3000
    - MONGO_URL=mongodb://mongo:27017/crimp
  links:
    - mongo:mongo
  ports:
    - 80:3000
